export const FETCH_CAPTURED_REQUESTS = 'FETCH_CAPTURED_REQUESTS';
export const FETCH_CAPTURED_REQUESTS_SUCCESS = 'FETCH_CAPTURED_REQUESTS_SUCCESS';

export const FETCH_SCENARIOS = 'FETCH_SCENARIOS';
export const FETCH_SCENARIOS_SUCCESS = 'FETCH_SCENARIOS_SUCCESS';
