export const FETCH_CAPTURED_REQUESTS         = 'FETCH_CAPTURED_REQUESTS';
export const FETCH_CAPTURED_REQUESTS_SUCCESS = 'FETCH_CAPTURED_REQUESTS_SUCCESS';

export const RECORD = 'RECORD';
export const STOP_RECORDING = 'STOP_RECORDING';

export const FETCH_MOCKED_REQUESTS         = 'FETCH_MOCKED_REQUESTS';
export const FETCH_MOCKED_REQUESTS_SUCCESS = 'FETCH_MOCKED_REQUESTS_SUCCESS';

export const TOGGLE_REQUEST = 'TOGGLE_REQUEST';

export const MOCK_REQUEST = 'MOCK_REQUEST';
export const UPDATE_MOCK  = 'UPDATE_MOCK';
export const REMOVE_MOCK  = 'REMOVE_MOCK';

export const NAVIGATE = 'NAVIGATE';

export const IMPORT = 'IMPORT';
