export const FETCH_CAPTURED_REQUESTS         = 'FETCH_CAPTURED_REQUESTS';
export const FETCH_CAPTURED_REQUESTS_SUCCESS = 'FETCH_CAPTURED_REQUESTS_SUCCESS';

export const RECORD = 'RECORD';
export const STOP_RECORDING = 'STOP_RECORDING';

export const FETCH_SCENARIOS         = 'FETCH_SCENARIOS';
export const FETCH_SCENARIOS_SUCCESS = 'FETCH_SCENARIOS_SUCCESS';
export const CREATE_NEW_SCENARIO     = 'CREATE_NEW_SCENARIO';
export const TOGGLE_SCENARIO         = 'TOGGLE_SCENARIO';
export const DUPLICATE_SCENARIO      = 'DUPLICATE_SCENARIO';
export const REMOVE_SCENARIO         = 'REMOVE_SCENARIO';
export const RENAME_SCENARIO         = 'RENAME_SCENARIO';

export const TOGGLE_REQUEST = 'TOGGLE_REQUEST';

export const MOCK_REQUEST = 'MOCK_REQUEST';
export const UPDATE_MOCK  = 'UPDATE_MOCK';
export const REMOVE_MOCK  = 'REMOVE_MOCK';

export const NAVIGATE = 'NAVIGATE';

export const IMPORT = 'IMPORT';
