export default {
  'Access-Control-Allow-Credentials': [],
  'Access-Control-Allow-Headers': [],
  'Access-Control-Allow-Methods': [],
  'Access-Control-Allow-Origin': [],
  'Access-Control-Expose-Headers': [],
  'Access-Control-Max-Age': [],
  'Accept-Patch': [],
  'Accept-Ranges': [],
  'Age': [],
  'Allow': [],
  'Alt-Svc': [],
  'Cache-Control': [],
  'Client-Date': [],
  'Client-Peer': [],
  'Client-Response-Num': [],
  'Connection': [],
  'Content-Disposition': [],
  'Content-Encoding': [],
  'Content-Language': [],
  'Content-Length': [],
  'Content-Location': [],
  'Content-MD5': [],
  'Content-Range': [],
  'Content-Type': [
    'application/javascript',
    'application/json',
    'application/x-www-form-urlencoded',
    'application/pdf',
    'application/xml',
    'application/zip',
    'multipart/form-data',
    'text/css',
    'text/html',
    'text/plain',
    'image/png',
    'image/jpeg',
    'image/gif'
  ],
  'Date': [],
  'ETag': [],
  'Expires': [],
  'Keep-Alive': [],
  'Last-Modified': [],
  'Link': [],
  'Location': [],
  'P3P': [],
  'Pragma': [],
  'Proxy-Authenticate': [],
  'Proxy-Connection': [],
  'Public-Key-Pins': [],
  'Refresh': [],
  'Retry-After': [],
  'Server': [],
  'Set-Cookie': [],
  'Status': [],
  'Strict-Transport-Security': [],
  'Timing-Allow-Origin': [],
  'Trailer': [],
  'Transfer-Encoding': [],
  'TSV': [],
  'Upgrade': [],
  'Vary': [],
  'Via': [],
  'Warning': [],
  'WWW-Authenticate': [],
  'X-Aspnet-Version': [],
  'X-Frame-Options': [],
  'X-Pingback': [],
  'X-XSS-protection': [],
  'Content-Security-Policy': [],
  'X-Content-Security-Policy': [],
  'X-Webkit-CSP': [],
  'Content-Security-Policy-Report-Only': [],
  'X-Content-Type-Options': [],
  'X-Powered-By': [],
  'X-UA-Compatible': [],
  'X-Content-Duration': [],
  'Upgrade-Insecure-Requests': [],
  'X-Request-ID': [],
  'X-Correlation-ID': []
}

const requestHeaders = {
  'Accept': [],
  'Accept-Charset': [],
  'Accept-Encoding': [],
  'Accept-Language': [],
  'Accept-Datetime': [],
  'Authorization': [],
  'Cache-Control': [],
  'Connection': [],
  'Cookie': [],
  'Content-Length': [],
  'Content-MD5': [],
  'Content-Type': [
    'application/javascript',
    'application/json',
    'application/x-www-form-urlencoded',
    'application/pdf',
    'application/xml',
    'application/zip',
    'multipart/form-data',
    'text/css',
    'text/html',
    'text/plain',
    'image/png',
    'image/jpeg',
    'image/gif'
  ],
  'Date': [],
  'Expect': [],
  'Forwarded': [],
  'From': [],
  'Host': [],
  'If-Match': [],
  'If-Modified-Since': [],
  'If-None-Match': [],
  'If-Range': [],
  'If-Unmodified-Since': [],
  'Max-Forwards': [],
  'Origin': [],
  'Pragma': [],
  'Proxy-Authorization': [],
  'Range': [],
  'Referer': [],
  'TE': [],
  'User-Agent': [],
  'Upgrade': [],
  'Via': [],
  'Warning': [],
  'X-Requested-Width': [],
  'DNT': [],
  'X-Forwarded-For': [],
  'X-Forwarded-Host': [],
  'X-Forwarded-Proto': [],
  'Front-End-Https': [],
  'X-Http-Method-Override': [],
  'X-ATT-DeviceId': [],
  'X-Wap-Profile': [],
  'Proxy-Connection': [],
  'X-UIDH': [],
  'X-Csrf-Token': [],
  'X-Request-Id': [],
  'X-Correlation-Id': []
};