const EVENTS = {
  SCENARIO_ADD: 'SCENARIO_ADD',
  SCENARIO_RENAME: 'SCENARIO_RENAME',
  SCENARIO_REMOVE: 'SCENARIO_REMOVE',
  SCENARIO_DUPLICATE: 'SCENARIO_DUPLICATE',
  SCENARIO_SET_ACTIVE: 'SCENARIO_SET_ACTIVE',
  SCENARIO_CHANGE: 'SCENARIO_CHANGE',
  SCENARIO_ADD_MOCKED_REQUEST: 'SCENARIO_ADD_MOCKED_REQUEST',

  REQUEST_CAPTURED: 'REQUEST_CAPTURED',

  MOCKED_REQUESTS_ADD: 'MOCKED_REQUESTS_ADD',

  IMPORT: 'IMPORT',

  STORAGE_PERSIST: 'STORAGE_PERSIST'
};


import { API } from 'api';
import { fetch, fetchScenarios } from 'ui/actions/api';

export function syncAPI({ dispatch }) {
  API.on(EVENTS.REQUEST_CAPTURED, () => dispatch(fetch()));
  API.on(EVENTS.SCENARIO_ADD, () => dispatch(fetchScenarios()));
  API.on(EVENTS.SCENARIO_CHANGE, () => dispatch(fetchScenarios()));
}
