const EVENTS = {
  SCENARIO_ADD: 'SCENARIO_ADD',
  SCENARIO_RENAME: 'SCENARIO_RENAME',
  SCENARIO_REMOVE: 'SCENARIO_REMOVE',
  SCENARIO_DUPLICATE: 'SCENARIO_DUPLICATE',
  SCENARIO_SET_ACTIVE: 'SCENARIO_SET_ACTIVE',
  SCENARIO_CHANGE: 'SCENARIO_CHANGE',
  SCENARIO_ADD_MOCKED_REQUEST: 'SCENARIO_ADD_MOCKED_REQUEST',

  REQUEST_CAPTURED: 'REQUEST_CAPTURED',

  MOCKED_REQUESTS_ADD: 'MOCKED_REQUESTS_ADD',

  IMPORT: 'IMPORT',

  STORAGE_PERSIST: 'STORAGE_PERSIST',

  BDSM_INIT: 'BDSM_INIT',
  BDSM_SET_DATA: 'BDSM_SET_DATA',
  GET_MOCKED_REQUESTS: 'GET_MOCKED_REQUESTS',

  BDSM_WEB_WORKER_CAPTURE: 'BDSM_WEB_WORKER_CAPTURE'
};

export default EVENTS;
