const EVENTS = {
  SCENARIO_ADD: 'SCENARIO_ADD',
  SCENARIO_RENAME: 'SCENARIO_RENAME',
  SCENARIO_REMOVE: 'SCENARIO_REMOVE',
  SCENARIO_DUPLICATE: 'SCENARIO_DUPLICATE',
  SCENARIO_SET_ACTIVE: 'SCENARIO_SET_ACTIVE',
  SCENARIO_CHANGE: 'SCENARIO_CHANGE',
  SCENARIO_ADD_MOCKED_REQUEST: 'SCENARIO_ADD_MOCKED_REQUEST',

  MOCKED_REQUESTS_ADD: 'MOCKED_REQUESTS_ADD',

  IMPORT: 'IMPORT',

  STORAGE_PERSIST: 'STORAGE_PERSIST'
};

export default EVENTS;
