const EVENTS = {
  RENAME_MOCKED_REQUEST: 'RENAME_MOCKED_REQUEST',
  REMOVE_MOCKED_REQUEST: 'REMOVE_MOCKED_REQUEST',
  DUPLICATE_MOCKED_REQUEST: 'DUPLICATE_MOCKED_REQUEST',
  MOCKED_REQUEST_CHANGE: 'MOCKED_REQUEST_CHANGE',
  ADD_MOCKED_REQUEST: 'ADD_MOCKED_REQUEST',

  START_RECORDING: 'START_RECORDING',
  STOPPED_RECORDING: 'STOPPED_RECORDING',

  REQUEST_CAPTURED: 'REQUEST_CAPTURED',
  RESPONSE_RECEIVED: 'RESPONSE_RECEIVED',

  IMPORT: 'IMPORT',

  STORAGE_PERSIST: 'STORAGE_PERSIST',
  STORAGE_READY: 'STORAGE_READY',

  MIMIC_INIT: 'MIMIC_INIT',
  MIMIC_SET_DATA: 'MIMIC_SET_DATA',
  GET_MOCKED_REQUESTS: 'GET_MOCKED_REQUESTS',

  MIMIC_WEB_WORKER_CAPTURE: 'MIMIC_WEB_WORKER_CAPTURE'
};

export default EVENTS;
